apiVersion: v1
kind: Service
metadata:
  name: bedrock-server
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 19132
    protocol: UDP
    targetPort: bedrock-server
  selector:
    bedrock: server