apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock-server
spec:
  replicas: 1
  selector:
    matchLabels:
      bedrock: server
  template:
    metadata:
      labels:
        bedrock: server
    spec:
      containers:
      - name: bedrock-server
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: bedrock-server
          containerPort: 19132
          protocol: UDP
        volumeMounts:
        - name: bedrock-data
          mountPath: /bedrock/worlds
        - name: bedrock-server-config
          mountPath: "/bedrock/server.properties"
          subPath: server.properties
      volumes:
      - name: bedrock-data
        persistentVolumeClaim:
          claimName: bedrock-server-pvc
      - name: bedrock-server-config
        configMap:
          name: bedrock-server-config
          items:
          - key: "server.properties"
            path: "server.properties"